In [1]:
import numpy as np
import pandas as pd

In [4]:
popolazione = pd.read_csv('data/popolazioneISTAT-regioni1gen2020.csv', sep=';')
popolazione

               Territorio   Maschi  Femmine    Totale
0                 Abruzzo   637388   668382   1305770
1              Basilicata   273941   282993    556934
2                Calabria   942644   982057   1924701
3                Campania  2820555  2965306   5785861
4          Emilia-Romagna  2174599  2292519   4467118
5   Friuli-Venezia Giulia   589215   622142   1211357
6                   Lazio  2832324  3033220   5865544
7                 Liguria   739021   804106   1543127
8               Lombardia  4949770  5154199  10103969
9                  Marche   738259   780141   1518400
10                 Molise   148764   153501    302265
11               Piemonte  2109314  2232061   4341375
12                 Puglia  1950256  2058040   4008296
13               Sardegna   800902   829572   1630474
14                Sicilia  2416233  2552177   4968410
15                Toscana  1798279  1924450   3722729
16     TrentinoAlto Adige   529824   544995   1074819
17                 Umbria   424592   455693    880285
18          Valle d'Aosta    61325    64176    125501
19                 Veneto  2403360  2504344   4907704

In [58]:
regioni = pd.read_csv('data/italy_regions.csv', sep=';', usecols=['regione', 'superficie'])
regioni

                  regione  superficie
0                 Abruzzo    10831.84
1              Basilicata    10073.32
2                Calabria    15221.90
3                Campania    13670.95
4          Emilia-Romagna    22452.78
5   Friuli-Venezia Giulia     7862.30
6                   Lazio    17232.29
7                 Liguria     5416.21
8               Lombardia    23863.65
9                  Marche     9401.38
10                 Molise     4460.65
11               Piemonte    25387.07
12                 Puglia    19540.90
13               Sardegna    24100.02
14                Sicilia    25832.39
15                Toscana    22987.04
16    Trentino-Alto Adige    13605.50
17                 Umbria     8464.33
18          Valle d'Aosta     3260.90
19                 Veneto    18407.42
20                    NaN         NaN

In [59]:
regioni.superficie = regioni['superficie']/1000
regioni.superficie.head()

0    10.83184
1    10.07332
2    15.22190
3    13.67095
4    22.45278
Name: superficie, dtype: float64

In [47]:
popolazione['Territorio'] = popolazione['Territorio'].replace('TrentinoAlto Adige', 'Trentino-Alto Adige')

In [50]:
ita = pd.merge(regioni, popolazione, left_on='regione', right_on='Territorio', how='inner').drop('Territorio', axis=1)
ita

                  regione  superficie   Maschi  Femmine    Totale
0                 Abruzzo    10.83184   637388   668382   1305770
1              Basilicata    10.07332   273941   282993    556934
2                Calabria    15.22190   942644   982057   1924701
3                Campania    13.67095  2820555  2965306   5785861
4          Emilia-Romagna    22.45278  2174599  2292519   4467118
5   Friuli-Venezia Giulia     7.86230   589215   622142   1211357
6                   Lazio    17.23229  2832324  3033220   5865544
7                 Liguria     5.41621   739021   804106   1543127
8               Lombardia    23.86365  4949770  5154199  10103969
9                  Marche     9.40138   738259   780141   1518400
10                 Molise     4.46065   148764   153501    302265
11               Piemonte    25.38707  2109314  2232061   4341375
12                 Puglia    19.54090  1950256  2058040   4008296
13               Sardegna    24.10002   800902   829572   1630474
14                Sicilia    25.83239  2416233  2552177   4968410
15                Toscana    22.98704  1798279  1924450   3722729
16    Trentino-Alto Adige    13.60550   529824   544995   1074819
17                 Umbria     8.46433   424592   455693    880285
18          Valle d'Aosta     3.26090    61325    64176    125501
19                 Veneto    18.40742  2403360  2504344   4907704

In [54]:
ita['densità']= ita['Totale']/ita['superficie']

In [55]:
ita

,regione,superficie,Maschi,Femmine,Totale,densità
0,Abruzzo,10.83184,637388,668382,1305770,120549.232633
1,Basilicata,10.07332,273941,282993,556934,55288.028177
2,Calabria,15.22190,942644,982057,1924701,126442.888207
3,Campania,13.67095,2820555,2965306,5785861,423223.038633
4,Emilia-Romagna,22.45278,2174599,2292519,4467118,198956.120356
5,Friuli-Venezia Giulia,7.86230,589215,622142,1211357,154071.582107
6,Lazio,17.23229,2832324,3033220,5865544,340380.994052
7,Liguria,5.41621,739021,804106,1543127,284909.004636
8,Lombardia,23.86365,4949770,5154199,10103969,423404.173293
9,Marche,9.40138,738259,780141,1518400,161508.204115
10,Molise,4.46065,148764,153501,302265,67762.545817
11,Piemonte,25.38707,2109314,2232061,4341375,171007.327746
12,Puglia,19.54090,1950256,2058040,4008296,205123.407827
13,Sardegna,24.10002,800902,829572,1630474,67654.466677
14,Sicilia,25.83239,2416233,2552177,4968410,192332.571628
15,Toscana,22.98704,1798279,1924450,3722729,161949.037371
16,Trentino-Alto Adige,13.60550,529824,544995,1074819,78998.860755
17,Umbria,8.46433,424592,455693,880285,103999.371480
18,Valle d'Aosta,3.26090,61325,64176,125501,38486.614125
19,Veneto,18.40742,2403360,2504344,4907704,266615.527869